variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode --errors --show-version"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean install -Dmaven.test.skip=true
  tags:
    - OracleJDK1.8

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  tags:
    - OracleJDK1.8

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy -Dmaven.test.skip=true
  tags:
    - OracleJDK1.8
  only:
    - master